on:
  workflow_dispatch:
    inputs:
      sprint_name:
        description: 'Sprint Name'
        required: true
      project_name:
        description: 'Project Name'
        required: true
      issues:
        description: 'Comma-separated list of issue keys'
        required: true

jobs:
  compute_kpi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install jira requests

      - name: Run KPI script
        run: |
          cd jira-kpi-to-sheets
          python story-points-closed.py \
            --sprint-name="${{ github.event.inputs.sprint_name }}" \
            --project-name="${{ github.event.inputs.project_name }}" \
            --issues='${{ github.event.inputs.issues }}'