on:
  workflow_dispatch:
    inputs:
      sprint_name:
        description: 'Sprint Name'
        required: true
      project_name:
        description: 'Project Name'
        required: true
      story_points_sum:
        description: 'Sum of Story Points'
        required: true

jobs:
  compute_kpi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: | 
            pip install jira requests
            cd jira-kpi-to-sheets
            python -m pip install --upgrade pip
            pip install -r requirements.txt
    
      - name: Setup Google Service Account
        env:
            GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        run: |
            echo "${GOOGLE_APPLICATION_CREDENTIALS}" | base64 --decode > ${{ github.workspace }}/service_account.json

      - name: Run KPI script
        run: |
          cd jira-kpi-to-sheets
          python story-point-closed.py \
            --sprint-name="${{ github.event.inputs.sprint_name }}" \
            --project-name="${{ github.event.inputs.project_name }}" \
            --story-points-sum='${{ github.event.inputs.story_points_sum }}'
        env:
            GOOGLE_APPLICATION_CREDENTIALS: ../service_account.json
